/**
 * Auto-generated–style type definitions for the Supabase schema.
 * Keep in sync with the SQL migration in `supabase/migrations/`.
 *
 * The shape follows the pattern generated by `supabase gen types typescript`.
 */

export type WaterLevel = "ankle" | "knee" | "waist" | "roof";
export type SosStatus = "pending" | "rescued";

export type FloodReport = {
  id: string;
  created_at: string;
  latitude: number;
  longitude: number;
  water_level: WaterLevel;
  description: string;
  image_url: string | null;
  verified: boolean;
};

export type SosRequest = {
  id: string;
  created_at: string;
  name: string;
  phone: string;
  latitude: number;
  longitude: number;
  people_count: number;
  needs: string[];
  status: SosStatus;
  /**
   * Set when a member of the public reports the rescue as complete. The
   * request stays `pending` until an operator confirms — the public cannot
   * write `status` at all (see migration 00008).
   */
  rescue_reported_at: string | null;
  rescue_reported_note: string | null;
};

/* ── Supabase-compatible Insert shapes ───────────────────────────────────── */

export type FloodReportInsert = {
  id?: string;
  created_at?: string;
  latitude: number;
  longitude: number;
  water_level: WaterLevel;
  description: string;
  image_url?: string | null;
  verified?: boolean;
};

export type SosRequestInsert = {
  id?: string;
  created_at?: string;
  name: string;
  phone: string;
  latitude: number;
  longitude: number;
  people_count: number;
  needs: string[];
  status?: SosStatus;
  rescue_reported_at?: string | null;
  rescue_reported_note?: string | null;
};

export type AdvisoryType = "critical" | "warning" | "info";

export type Advisory = {
  id: string;
  created_at: string;
  title: string;
  message: string;
  type: AdvisoryType;
  link: string | null;
};

export type AdvisoryInsert = {
  id?: string;
  created_at?: string;
  title: string;
  message: string;
  type: AdvisoryType;
  link?: string | null;
};

/* ── Database schema type for createClient<Database>() ───────────────────── */

export type Database = {
  public: {
    Tables: {
      flood_reports: {
        Row: FloodReport;
        Insert: FloodReportInsert;
        Update: Partial<FloodReportInsert>;
        Relationships: [];
      };
      sos_requests: {
        Row: SosRequest;
        Insert: SosRequestInsert;
        Update: Partial<SosRequestInsert>;
        Relationships: [];
      };
      advisories: {
        Row: Advisory;
        Insert: AdvisoryInsert;
        Update: Partial<AdvisoryInsert>;
        Relationships: [];
      };
    };
    Views: Record<
      string,
      {
        Row: Record<string, unknown>;
        Relationships: never[];
      }
    >;
    Functions: Record<
      string,
      {
        Args: Record<string, unknown>;
        Returns: unknown;
      }
    >;
    Enums: {
      water_level: WaterLevel;
      sos_status: SosStatus;
      advisory_type: AdvisoryType;
    };
    CompositeTypes: Record<string, never>;
  };
};
